format_version: v1.0
type: UniqueComponent
attributes: {id: eeprom}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: EEPROM_CFGCON_EEWS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: eeprom, value: '2'}
- type: ElementPosition
  attributes: {x: '24', y: '289', id: eeprom}
